queue_machine/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import RedirectView
from django.conf import settings



urlpatterns = [
    path('', RedirectView.as_view(url='queuemachine/')),
    path('favicon.ico',RedirectView.as_view(url=settings.STATIC_URL+'queue_app/images/favicon.png')),
    path('admin/', admin.site.urls),
    path('queuemachine/', include('queue_app.queue_urls')),
    path('queuemachine/', include('django.contrib.auth.urls')),
]

queue_app/models.py
from django.db import models
from django.utils.translation import gettext_lazy as _
from datetime import date
from django.contrib.auth.models import AbstractUser, Group
import uuid


class Organization(models.Model):
    id = models.UUIDField(
        primary_key=True,
        default=uuid.uuid4,
        editable=False,
    )
    date_created = models.DateTimeField(auto_now_add=True)

    date_modified = models.DateTimeField(auto_now=True)

    name = models.CharField(
        max_length=20,
        verbose_name=_('name'),
    )

    def __str__(self):
        return self.name

    def to_flat_dict(self):
        return {
            'id': str(self.id),
            'name': self.name,
        }

    class Meta:
        verbose_name = _('organization')
        verbose_name_plural = verbose_name


class CounterBooth(models.Model):
    id = models.UUIDField(
        primary_key=True,
        default=uuid.uuid4,
        editable=False,
    )

    groups = models.ForeignKey(
        Group,
        blank=True,
        related_name='booths',
        on_delete=models.CASCADE,
        null=True,
        verbose_name=_('groups'),
    )

    display_name = models.CharField(
        max_length=20,
        verbose_name=_('display name'),
    )

    spoken_name = models.CharField(
        max_length=30,
        verbose_name=_('spoken name'),
    )

    desc = models.CharField(
        max_length=200,
        null=True,
        blank=True,
        verbose_name=_('description'),
    )

    date_created = models.DateTimeField(auto_now_add=True)

    date_modified = models.DateTimeField(auto_now=True)

    organization = models.ForeignKey(
        Organization,
        on_delete=models.CASCADE,
        related_name='counter_booth',
        null=False,
        blank=False,
        verbose_name=_('organization'),
    )

    def __str__(self):
        return self.display_name

    def to_flat_dict(self):
        return {
            'id': str(self.id),
            'display_name': self.display_name,
            'spoken_name': self.spoken_name,
            'desc': self.desc,
            'organization': str(self.organization.id or 'null'),
            # 'group': str(self.groups.id or 'null'),
        }

    def latest_queue(self):
        return self.queues.today_filter().order_by('date_modified').last()

    class Meta:
        verbose_name = _('counter booth')
        verbose_name_plural = verbose_name


class User(AbstractUser):
    id = models.UUIDField(
        primary_key=True,
        default=uuid.uuid4,
        editable=False
    )

    organization = models.ManyToManyField(
        Organization,
        related_name='users',
        blank=False,
        verbose_name=_('organization')
    )

    phone = models.CharField(
        null=True,
        blank=True,
        max_length=12,
        verbose_name=_('phone number')
    )

    def __str__(self):
        return self.username


# class CustomerProfile(models.Model):
# 	id=models.UUIDField(
# 		primary_key=True,
# 		default=uuid.uuid4,
# 		editable=False
# 	)
#
# 	user=models.OneToOneField(
# 		User,
# 		on_delete=models.CASCADE,
# 		related_name='customer_profile'
# 	)
#
# 	groups=models.ManyToManyField(
# 		Group,
# 		blank=True,
# 		related_name='customers',
# 	)
#
# 	birth_modified=models.DateTimeField(null=True,blank=True)
#
# 	first_name = models.CharField(max_length=20)
#
# 	last_name = models.CharField(max_length=20)
#
# 	email = models.EmailField()
#
# 	address = models.CharField(max_length=200)
#
# 	phone=models.CharField(
# 		null=True,
# 		blank=True,
# 		max_length = 12,
# 	)
#
# 	date_created=models.DateTimeField(auto_now_add=True)
#
# 	date_modified=models.DateTimeField(auto_now=True)

class ServiceQueryset(models.QuerySet):
    """docstring for ServiceQueryset."""

    def get_last_queue(self):
        return self.queues.last()

    def groups_filter(self, iterable):
        return self.filter(group__in=iterable)

    def group_filter(self, group_obj):
        return self.filter(group=group_obj)

    def org_filter(self, org):
        return self.filter(organization=org)

    def orgs_filter(self, orgs):
        return self.filter(organization__in=orgs)

    def is_hidden(self, flag=None):
        if flag is not None:
            return self.filter(is_hidden=flag)
        return self


class Service(models.Model):
    id = models.UUIDField(
        primary_key=True,
        default=uuid.uuid4,
        editable=False,
    )

    date_created = models.DateTimeField(auto_now_add=True)

    date_modified = models.DateTimeField(auto_now=True)

    organization = models.ForeignKey(
        Organization,
        on_delete=models.CASCADE,
        related_name='services',
        null=False,
        # null=True,
        blank=False,
        verbose_name=_('organization'),
    )

    group = models.ForeignKey(
        Group,
        on_delete=models.CASCADE,
        null=True,
        blank=True,
        related_name='services',
        verbose_name=_('group'),
    )

    name = models.CharField(
        max_length=30,
        verbose_name=_('name'),
    )

    desc = models.CharField(
        max_length=200,
        null=True,
        blank=True,
        verbose_name=_('description'),
    )

    queue_char = models.CharField(
        null=True,
        blank=True,
        max_length=1,
        verbose_name=_('queue character'),
    )

    is_hidden = models.BooleanField(default=False, verbose_name=_('hide'))

    objects = ServiceQueryset.as_manager()

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = _('service')
        verbose_name_plural = verbose_name


class QueueQueryset(models.QuerySet):
    def today_filter(self):
        return self.filter(date_created__date=date.today())

    def is_printed(self, flag=None):
        if flag is not None:
            return self.filter(is_printed=flag)
        return self

    def is_booking(self, flag=None):
        if flag is not None:
            return self.filter(is_booking=flag)
        return self

    def is_called(self, flag=None):
        if flag is not None:
            return self.filter(is_called=flag)
        return self

    def is_finished(self, flag=None):
        if flag is not None:
            return self.filter(is_finished=flag)
        return self

    def services_filter(self, iterable):
        return self.filter(service__in=iterable)

    def last_modified(self):
        return self.order_by('date_modified').last()


class Queue(models.Model):
    id = models.UUIDField(
        primary_key=True,
        default=uuid.uuid4,
        editable=False
    )

    date_created = models.DateTimeField(auto_now_add=True, verbose_name=_('date created'))

    date_modified = models.DateTimeField(auto_now=True, verbose_name=_('date modified'))

    service = models.ForeignKey(
        Service,
        on_delete=models.CASCADE,
        related_name='queues',
        null=False,
        blank=False,
        verbose_name=_('service'),
    )  #

    character = models.CharField(
        null=True,
        blank=True,
        max_length=1,
        verbose_name=_('character'),

    )

    # calculated by forms
    number = models.IntegerField(
        null=True,
        blank=True,
        verbose_name=_('number'),
    )

    customer = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        null=True,
        blank=True,
        related_name='queues',
        verbose_name=_('customer'),

    )  #

    counter_booth = models.ForeignKey(
        CounterBooth,
        on_delete=models.SET_NULL,
        null=True,
        blank=True,
        related_name='queues',
        verbose_name=_('counter'),

    )  #

    is_booking = models.BooleanField(default=False, verbose_name=_('booking'))  #

    is_called = models.BooleanField(default=False, verbose_name=_('called'))  #

    is_printed = models.BooleanField(default=False, verbose_name=_('printed'))  #

    is_finished = models.BooleanField(default=False, verbose_name=_('finished'))  #

    booking_datetime = models.DateTimeField(null=True, blank=True, verbose_name=_('booking date time'))

    print_datetime = models.DateTimeField(null=True, blank=True, verbose_name=_('print date time'))

    objects = QueueQueryset.as_manager()

    def __str__(self):
        return self.service.name + '/' + str(self.number) + '/' + str(self.pk)

    def save(self, *args, **kwargs):
        self.character = self.character or self.service.queue_char
        super().save(*args, **kwargs)

    class Meta:
        ordering = ['date_created']
        verbose_name = _('queue')
        verbose_name_plural = verbose_name

queue_app/forms.py
'''
Created on Oct 1, 2018

@author: gallantino
'''
from django import forms
from django.contrib.auth.forms import UserCreationForm, UserChangeForm, PasswordChangeForm
from queue_app import models
from dal import autocomplete
from datetime import datetime
from random import randint
from django.db.utils import IntegrityError
from django.utils.translation import gettext_lazy as _


class BaseMedia:
    css = {
        'all': (
            'queue_app/bootstrap/css/bootstrap.min.css',
            'queue_app/font-awesome/css/font-awesome.min.css',
            'queue_app/jquery-ui/jquery-ui.min.css',
            'queue_app/jquery-timepicker/jquery.timepicker.min.css',
        ),
    }
    js = (
        'queue_app/jquery-ui/jquery-ui.min.js',
        'queue_app/jquery-timepicker/jquery.timepicker.min.js',
    )


class CustomUserCreationForm(UserCreationForm):
    class Meta(UserCreationForm.Meta):
        model = models.User
        fields = ('username', 'password1', 'password2',)


class CustomUserChangeForm(UserChangeForm):
    class Meta(UserChangeForm.Meta):
        model = models.User


class CustomerCreationForm(CustomUserCreationForm):
    def __init__(self, *args, **kwargs):
        super(CustomerCreationForm, self).__init__(*args, **kwargs)
        self.fields['password1'].required = False
        self.fields['password2'].required = False

    def save(self, commit=True):
        new_customer = super(CustomerCreationForm, self).save(commit=False)
        new_customer.username = self.cleaned_data.get('first_name') + self.cleaned_data.get('last_name')
        new_customer.set_unusable_password()
        if commit:
            try:
                new_customer.save()
            except IntegrityError:
                new_customer.username = new_customer.username + str(randint(0, 100))
                new_customer.save()
            self.save_m2m()
        return new_customer

    class Meta(CustomUserCreationForm.Meta):
        fields = (
            'first_name',
            'last_name',
            'email',
            'phone',
            'organization',
        )

        labels = {
            'first_name': _('first name'),
            'last_name': _('last name'),
            'email': _('email address'),
            'phone': _('phone'),
            'organization': _('organization')
        }

        widgets = {
            'organization': autocomplete.ModelSelect2Multiple(
                url='queue:manager:organization_autocomplete',
                attrs={
                    'id': 'organization',
                    'data-placeholder': _('organization'),
                },
            ),
        }

    class Media:
        css = {
            'all': (
                'queue_app/bootstrap/css/bootstrap.min.css',
                'queue_app/jquery-ui/jquery-ui.min.css',
                'queue_app/core/css/manager-form.css'
            ),
        }
        js = (
            'queue_app/jquery-ui/jquery-ui.min.js',
        )


class EmployeeChangeForm(CustomUserChangeForm):
    # def __init__(self, *args, **kwargs):
    #     super(EmployeeChangeForm,self).__init__(*args, **kwargs)
    class Meta(CustomUserChangeForm.Meta):
        fields = (
            'first_name',
            'last_name',
            'username',
            'email',
            'phone',
            'password',
        )

        labels = {
            'first_name': _('first name'),
            'last_name': _('last name'),
            'username': _('user name'),
            'email': _('email address'),
            'phone': _('phone'),
        }

    class Media:
        css = {
            'all': (
                'queue_app/bootstrap/css/bootstrap.min.css',
                'queue_app/jquery-ui/jquery-ui.min.css',
                'queue_app/core/css/manager-form.css'
            ),
        }
        js = (
            'queue_app/jquery-ui/jquery-ui.min.js',
        )


class EmployeePasswordChangeForm(PasswordChangeForm):
    class Media:
        css = {
            'all': (
                'queue_app/bootstrap/css/bootstrap.min.css',
                'queue_app/core/css/manager-form.css'
            ),
        }


class QueueModelBaseForms(forms.ModelForm):
    booking_time = forms.TimeField(
        label=_("booking time"),
        initial=datetime.now(),
        required=False,
        widget=forms.TimeInput(
            format='%H:%M',
            attrs={
                'id': 'booking-time',
                'class': 'input-field',
            },
        ),
    )

    booking_date = forms.DateField(
        label=_("booking date"),
        initial=datetime.now(),
        required=False,
        widget=forms.DateInput(
            format='%d-%m-%Y',
            attrs={
                'id': 'booking-date',
                'class': 'input-field',
            },
        ),
    )

    class Meta:
        model = models.Queue
        fields = '__all__'

        widgets = {
            'service': autocomplete.ModelSelect2(
                url='queue:manager:service_autocomplete',
                attrs={
                    'id': 'service',
                    'data-placeholder': _('service'),
                    'data-minimum-input-length': 1,
                },
            ),
            'customer': autocomplete.ModelSelect2(
                url='queue:manager:user_autocomplete',
                attrs={
                    'id': 'service',
                    'data-placeholder': _('customer'),
                    'data-minimum-input-length': 3,
                },
            ),
        }

    class Media:
        css = {
            'all': (
                'queue_app/bootstrap/css/bootstrap.min.css',
                'queue_app/font-awesome/css/font-awesome.min.css',
                'queue_app/core/css/manager-form.css',
                'queue_app/jquery-ui/jquery-ui.min.css',
                'queue_app/jquery-timepicker/jquery.timepicker.min.css',
            ),
        }
        js = (
            'queue_app/jquery-ui/jquery-ui.min.js',
            'queue_app/jquery-timepicker/jquery.timepicker.min.js',
        )

    def save(self, commit=True):
        # get models.Queue isntance to create or edit
        new_queue = super(QueueModelBaseForms, self).save(commit=False)
        if self.cleaned_data.get('is_booking', False):
            try:
                # get booking data
                new_queue.booking_datetime = datetime.combine(
                    self.cleaned_data.pop('booking_date'),
                    self.cleaned_data.pop('booking_time')
                )
            except Exception:
                pass

        # define queue number automaticly
        if self.cleaned_data.pop('is_printed', False):
            # get latest queue
            recent_queue = (
                models.Queue.objects
                    .filter(service=new_queue.service)
                    # .is_booking(self.cleaned_data.get('booking_flag', False))
                    .today_filter()
                    .is_printed(True)
                    .order_by('print_datetime')
                    .last()
            )
            new_queue.number = new_queue.number or (getattr(recent_queue, 'number', None) or 0) + 1
            new_queue.print_datetime = new_queue.print_datetime or datetime.now()
        # save when commited
        if commit:
            new_queue.save()
        return new_queue


class AddQueueModelForms(QueueModelBaseForms):
    class Meta(QueueModelBaseForms.Meta):
        fields = ('service', 'is_printed',)


class AddBookingQueuemodelForms(QueueModelBaseForms):
    class Meta(QueueModelBaseForms.Meta):
        fields = ('service', 'customer', 'is_booking')


class PrintQueueModelForms(QueueModelBaseForms):
    class Meta(QueueModelBaseForms.Meta):
        fields = ('is_printed',)


class FinishQueueModelForms(QueueModelBaseForms):
    class Meta(QueueModelBaseForms.Meta):
        fields = ('is_finished',)


class CallQueueModelForms(QueueModelBaseForms):
    class Meta(QueueModelBaseForms.Meta):
        fields = ('is_called', 'counter_booth')

    def save(self, commit=True):
        new_queue = super(CallQueueModelForms, self).save(commit=False)
        new_queue.is_called = self.cleaned_data.pop('is_called', new_queue.is_called)
        if commit:
            new_queue.save()
        return new_queue


class MoveQueueModelForms(QueueModelBaseForms):
    class Meta(QueueModelBaseForms.Meta):
        fields = ('service',)

    def save(self, commit=True):
        # make it look like its reprinted
        new_queue = super(MoveQueueModelForms, self).save(commit=False)
        new_queue.print_datetime = datetime.now()
        new_queue.is_called = False
        if commit:
            new_queue.save()
        return new_queue

queue_app/templates/queue_app/manager/add_booking_form.html
{% extends "queue_app/manager/manager_base.html" %}
{% load i18n %}
{% load static %}
{% load widget_tweaks %}
{% block title %}
	QM &#183; Add Booking
{% endblock %}
{% block stylesheet-content %}
	{{ form.media }}
{% endblock %}

{% block content %}
<body style="margin-top:0">
	<div class="container-fluid form-container" id="form-container" style="margin-top:0">
		<form id="add-booking-form" action="{% url "queue:manager:add_booking" %}" method="POST">
			{% csrf_token %}
			<input type="hidden" name="is_booking" value="True"/>
			<div class ="form-group">
				<label for="service">{{ form.service.label|capfirst }} </label>
				{{ form.service }}
			</div>
			<div class ="form-group">
				<label for="id_customer">{{ form.customer.label|capfirst }} </label>
				{{ form.customer|attr:"required" }}
			</div>
			<div class ="form-group">
				<label for="booking-time">{{ form.booking_time.label|capfirst }} </label>
				{{ form.booking_time|attr:"required"|add_class:"form-control" }}
			</div>
			<div class ="form-group">
				<label for="booking-date">{{ form.booking_date.label|capfirst }} </label>
				{{ form.booking_date|attr:"required "|add_class:"form-control" }}
			</div>
			<button type="submit" class="form-control">SUBMIT</button>
		</form>

		{% if form.errors %}
		<div id="form-error" class="alert alert-warning fade show mt-3" role="alert">
			{% trans "the operation could not be performed because one or more error(s) occurred." as err1_tx %}
			{% trans "please resubmit the form after making the following changes:" as err2_tx%}
			<p>{{err1_tx|capfirst}}<br/>{{err2_tx|capfirst}}</p>
			<ul>
			{% for field in form %}
				{% if field.errors %}<li>{{ field.label|title }}: {{ field.errors|striptags }}</li>{% endif %}
			{% endfor %}
			</ul>
		</div>
		{% endif %}
	</div>
{% endblock %}

{% block javascript-content %}
<script type="text/javascript">
$(document).ready(function(){
		$('#booking-time').timepicker({
			timeFormat: 'HH:mm',
			dropdown: false,
		});
		$( "#booking-date" ).datepicker({
		buttonText: "Select date",
		dateFormat:"d-m-yy",
		});
});

</script>
{% endblock %}

queue_app/templates/queue_app/manager/add_customer_form.html
{% extends "queue_app/manager/manager_base.html" %}
{% load i18n %}
{% load static %}
{% load widget_tweaks %}

{% block stylesheet-content %}
{{ form.media }}
{% endblock %}
{% block title %}
	QM &#183; Add Booking
{% endblock %}
{% block content %}
	<div class="container-fluid form-container">
		<form id="add-booking-form" action="{% url "queue:manager:add_customer" %}" method="POST">
			{% csrf_token %}
			<div class="form-row">
				<div class="col">
					<div class ="form-group">
						<label for="id_first_name">{{ form.first_name.label|capfirst }} </label>
						<div>{{ form.first_name|attr:"required"|add_class:"form-control" }}</div>
					</div>
				</div>
				<div class="col">
					<div class ="form-group">
						<label for="id_last_name">{{ form.last_name.label|capfirst }} </label>
						<div>{{ form.last_name|add_class:"form-control" }}</div>
					</div>
				</div>
			</div>
			<div class ="form-group">
				<label for="id_email">{{ form.email.label|capfirst }} </label>
				<div>{{ form.email|attr:"required"|add_class:"form-control" }}</div>
			</div>
			<div class ="form-group">
				<label for="id_phone">{{ form.phone.label|capfirst }} </label>
				<div>{{ form.phone|add_class:"form-control" }}</div>
			</div>
			<div class ="form-group">
				<label for="organization">{{ form.organization.label|capfirst }} </label>
				<div>{{ form.organization|attr:"required" }}</div>
			</div>
			<button type="submit" class="form-control">SUBMIT</button>
		</form>
		{% if form.errors %}
		<div id="form-error" class="alert alert-warning alert-dismissible fade show" role="alert">
			{% trans "the operation could not be performed because one or more error(s) occurred." as erra_tx %}
			{% trans "please resubmit the form after making the following changes:" as errb_tx %}
			<p>{{err1_tx|capfirst}}<br/>{{err2_tx|capfirst}}</p>
			<ul>
			{% for field in form %}
				{% if field.errors %}<li>{{field.label}}: {{ field.errors|striptags }}</li>{% endif %}
			{% endfor %}
			</ul>
		</div>
		{% endif %}
	</div>
{% endblock %}

{% block javascript-content %}
<script type="text/javascript">

</script>
{% endblock %}

queue_app/templates/queue_app/manager/booth_list.html
{% if  CounterBooths %}
	{% for booth in CounterBooths %}
		{% if  request.session.CounterBooth.id  == booth.id|stringformat:"s" %}
			<a class="dropdown-item disabled" href="{% url "queue:manager:session_booth" booth.id %}?next={{ request.get_full_path|urlencode }}">{{ booth.display_name }}</a>
		{% else %}
			<a class="dropdown-item" href="{% url "queue:manager:session_booth" booth.id %}?next={{ request.get_full_path|urlencode }}">{{ booth.display_name }}</a>
		{% endif %}
	{% endfor %}
{% else %}
	Pilih organisasi dahulu
{% endif %}

queue_app/templates/queue_app/manager/change_password_form.html
{% extends "queue_app/manager/manager_base.html" %}
{% load i18n %}
{% load static %}
{% load widget_tweaks %}

{% block stylesheet-content %}
{{ form.media }}
{% endblock %}
{% block content %}
	<div class="container-fluid form-container">
		<form id="add-booking-form" action="{% url "queue:manager:change_password" %}" method="POST">
			{% csrf_token %}
			<div class ="form-group">
				<label for="id_old_pasword">{{ form.old_password.label|capfirst }} </label>
				<div>{{ form.old_password|attr:"required"|add_class:"form-control" }}</div>
			</div>
			<div class ="form-group">
				<label for="new_pasword1">{{ form.new_password1.label|capfirst }} </label>
				<div>{{ form.new_password1|attr:"required"|add_class:"form-control" }}</div>
				<small class="form-text text-muted">
					{{form.new_password1.help_text}}
				</small>
			</div>
			<div class ="form-group">
				<label for="new_pasword2">{{ form.new_password2.label|capfirst }} </label>
				<div>{{ form.new_password2|add_class:"form-control" }}</div>
			</div>
			{% comment %}
			<div class ="form-group">
				<label for="organization">{{ form.password.label|capfirst }} </label>
				<div>{{ form.password }}</div>
			</div>
			{% endcomment %}

			<button type="submit" class="form-control">SUBMIT</button>
		</form>
		{% if form.errors %}
		<div id="form-error" class="alert alert-warning alert-dismissible fade show" role="alert">
			{% trans "the operation could not be performed because one or more error(s) occurred." as erra_tx %}
			{% trans "please resubmit the form after making the following changes:" as errb_tx %}
			<p>{{err1_tx|capfirst}}<br/>{{err2_tx|capfirst}}</p>
			<ul>
			{% for field in form %}
				{% if field.errors %}<li>{{field.label}}: {{ field.errors|striptags }}</li>{% endif %}
			{% endfor %}
			</ul>
		</div>
		{% endif %}
	</div>
{% endblock %}

{% block javascript-content %}
<script type="text/javascript">

</script>
{% endblock %}

queue_app/templates/queue_app/manager/edit_user_form.html
{% extends "queue_app/manager/manager_base.html" %}
{% load i18n %}
{% load static %}
{% load widget_tweaks %}
{% block title %}Edit profile{% endblock %}

{% block stylesheet-content %}
{{ form.media }}
{% endblock %}
{% block content %}
	<div class="container-fluid form-container">
		<form id="add-booking-form" action="{% url "queue:manager:edit_user" %}" method="POST">
			{% csrf_token %}
			<div class="form-row">
				<div class="col">
					<div class ="form-group">
						<label for="id_first_name">{{ form.first_name.label|capfirst }} </label>
						<div>{{ form.first_name|attr:"required"|add_class:"form-control" }}</div>
					</div>
				</div>
				<div class="col">
					<div class ="form-group">
						<label for="id_last_name">{{ form.last_name.label|capfirst }} </label>
						<div>{{ form.last_name|add_class:"form-control" }}</div>
					</div>
				</div>
			</div>
			<div class ="form-group">
				<label for="id_username">{{ form.username.label|capfirst }} </label>
				<div>{{ form.username|attr:"required"|add_class:"form-control" }}</div>
			</div>
			<div class ="form-group">
				<label for="id_email">{{ form.email.label|capfirst }} </label>
				<div>{{ form.email|attr:"required"|add_class:"form-control" }}</div>
			</div>
			<div class ="form-group">
				<label for="id_phone">{{ form.phone.label|capfirst }} </label>
				<div>{{ form.phone|add_class:"form-control" }}</div>
			</div>
			<div class ="form-group">
				<label for="organization">{{ form.password.label|capfirst }} </label>
				<div>{{ form.password }}</div>
			</div>
			<a class="btn btn-secondary mb-3" role="button"href="{% url 'queue:manager:change_password' %}">
				{% trans "change password" as c_p_tx%}{{c_p_tx|upper}}
			</a>
			<button type="submit" class="form-control btn btn-primary">SUBMIT</button>
		</form>
		{% if form.errors %}
		<div id="form-error" class="alert alert-warning alert-dismissible fade show" role="alert">
			{% trans "the operation could not be performed because one or more error(s) occurred." as erra_tx %}
			{% trans "please resubmit the form after making the following changes:" as errb_tx %}
			<p>{{err1_tx|capfirst}}<br/>{{err2_tx|capfirst}}</p>
			<ul>
			{% for field in form %}
				{% if field.errors %}<li>{{field.label}}: {{ field.errors|striptags }}</li>{% endif %}
			{% endfor %}
			</ul>
		</div>
		{% endif %}
	</div>
{% endblock %}

{% block javascript-content %}
<script type="text/javascript">

</script>
{% endblock %}

queue_app/templates/queue_app/manager/organization_list.html
{% if Organizations %}
	{% for organization in Organizations %}
		{% if  request.session.Organization.id  == organization.id|stringformat:"s" %}
			<a class="dropdown-item disabled" href="{% url 'queue:manager:session_org' organization.id %}?next={{ request.get_full_path|urlencode }}">{{ organization.name }}</a>
		{% else %}
			<a class="dropdown-item" href="{% url 'queue:manager:session_org' organization.id %}?next={{ request.get_full_path|urlencode }}">{{ organization.name }}</a>
		{% endif %}
	{% endfor %}
{% else %}
	No Data
{% endif %}

queue_app/templates/queue_app/manager/user_lookup.html
<ul>
{% for user in users %}
	<li>
		{{ user.username }}
	</li>
{% endfor %}
</ul>